name: Go
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'cmd/**' # Ignore changes to the Lua code
      - 'go.sum'
      - 'go.mod'
jobs:
  go_lint:
    name: Lint Go ðŸ’… 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
          only-new-issues: true
          skip-cache: true
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2024.1.1
      - name: Run staticcheck
        run: staticcheck ./...
  go_test:
    name: Test Go ðŸ§ª 
    needs: [go_lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Build
      run: make compile
    - name: Test
      run: make test
